server:
  port: 8001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.128:8848
  application:
      name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      password: 123456
      database: 0
      timeout: 10000ms
      connect-timeout: 10000ms

  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
short-link:
  stats:
    local:
      amap-key: 3cb92daf687cb1909f67c74b62073220
  domain:
    default: nurl.ink:8001
  goto-domain:
    enable: true
    names: '百度,github,stackoverflow,codeforce,google'
    details:
      - baidu.com
      - github.com
      - stackoverflow.com
      - codeforce.com
